########################################################################################
#                                    SETUP  WORDPRESS                                  #
########################################################################################

services:
  db:
    container_name: wordpress-mysql-1
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - wordpress-network
    
  wordpress:
    container_name: wordpress-1
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-network
    depends_on:
      - db


########################################################################################
volumes:
  mysql-db-volume:
########################################################################################

########################################################################################
networks:
  wordpress-network:
    driver: bridge
########################################################################################
